# NumPy

arr = np.array([ [1,2,3], [4,5,6] ])     
arr = np.full((2,3), 100) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; arr = np.zeros((2,3))  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   arr = np.ones((2,3,2)) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; arr = np.identity(3) <br>
arr = np.random.rand(2,3) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; arr = np.random.randint(100, 200, size=(2,3)) <br>
arr2 = arr1.copy()
_______________________
new_arr = np.repeat(arr, 4, axis=0) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  new_arr = np.repeat(arr, 4, axis=1) <br>
new_arr = np.vstack([v1, v2, v2]) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; new_arr = np.hstack([h1, h2])
_______________________
arr.ndim &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; arr.shape <br>
arr.dtype <br>
arr.size &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; arr.itemsize <br>
_______________________
arr[1, 5] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; arr[1, :] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; arr[:, 5] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; arr[0, ::2]
_______________________

np.sin(arr) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  np.cos(arr) <br>
np.matmul(arr1, arr2) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; OR &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; arr1 @ arr2 <br>
np.linalg.det(arr) <br>
np.min(arr) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; np.min(arr, axis=0) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; np.min(arr, axis=1) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; np.max(arr) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; np.sum(arr) <br>

##### Masking ↓ 

In [1]:
import numpy as np

arr1 = np.array([5, 6, 7])
arr2 = np.array([[5, 6, 7], [8, 9, 10]])

In [2]:
arr2.ndim        # No of dimensions

2

In [3]:
arr2.shape

(2, 3)

In [4]:
arr1.dtype       # default 'int32'

dtype('int32')

In [5]:
arr3 = np.array([5,6,7], dtype='int16')
arr3.dtype

dtype('int16')

In [6]:
arr2.itemsize # size of each elements (byte)

4

In [7]:
arr2.size # no of elements

6

In [8]:
arr2.nbytes # total_size 
# arr2.itemsize * arr2.size

24

# Access

In [9]:
arr = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [10]:
arr[1, 5]
# arr[-1, -2], arr[1][5] 

13

In [11]:
 arr[1, :] # row

array([ 8,  9, 10, 11, 12, 13, 14])

In [12]:
arr[:, 0] # column

array([1, 8])

In [13]:
# [ startindex : endindex : stepsize ]
arr[0, ::2]

array([1, 3, 5, 7])

# Initialize

In [14]:
a = np.full((2,3), 100, dtype='int16')            
print(a)

[[100 100 100]
 [100 100 100]]


In [15]:
b = np.full(a.shape, 50)
print(b)
# d = np.full_like(c, 50)

[[50 50 50]
 [50 50 50]]


In [16]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
b = np.ones((2,2,4))
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [18]:
np.identity(3)
# or
# np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random Initialization

In [19]:
# b/w 0 & 1
np.random.rand(2,3)   # np.random.rand(d.shape)

array([[0.45399655, 0.99106257, 0.95809653],
       [0.41227145, 0.22329082, 0.79549836]])

In [20]:
# int
np.random.randint(100, 200, size=(2,3))

array([[163, 101, 129],
       [154, 152, 180]])

# Repeat / Extend

In [21]:
arr = np.array([5,6,7]) # 1D
r1 = np.repeat(arr, 4)
print(r1)

[5 5 5 5 6 6 6 6 7 7 7 7]


In [22]:
arr = np.array([[5,6,7]]) # 2D
r1 = np.repeat(arr, 4, axis=0)
print(r1)

[[5 6 7]
 [5 6 7]
 [5 6 7]
 [5 6 7]]


In [23]:
arr = np.array([[5,6,7]]) # 2D
r1 = np.repeat(arr, 4, axis=1)
print(r1)

[[5 5 5 5 6 6 6 6 7 7 7 7]]


# Copy

In [24]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [25]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [26]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = arr1[[1,2,7]]
print(arr2)

[2 3 8]


#  Calculation

In [27]:
a = np.array([1,2,3,4])

In [28]:
a+2 # a+=2 // to keep changes

array([3, 4, 5, 6])

In [29]:
a-1 # a-=1

array([0, 1, 2, 3])

In [30]:
a*2 # a*=2

array([2, 4, 6, 8])

In [31]:
a/2 # a/=2

array([0.5, 1. , 1.5, 2. ])

In [32]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [33]:
b = np.array([4,3,2,1])
a+b

array([5, 5, 5, 5])

In [34]:
a*b

array([4, 6, 6, 4])

In [35]:
np.sin(a)
# np.cos(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [36]:
# dot product
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
np.dot(a, b)

14

In [37]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
a*b

array([1, 4, 9])

# Matrix Multiplication

In [38]:
a = np.full((2,3),2)
b = np.full((3,2),1)
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [39]:
# or
a = np.full((2,3),2)
b = np.full((3,2),1)
a @ b

array([[6, 6],
       [6, 6]])

# Determinant

In [40]:
c = np.identity(3)
np.linalg.det(c)

1.0

# min, max, sum

In [41]:
stats = np.array([[1,2,3],[4,5,6]])

In [42]:
np.min(stats)

1

In [43]:
np.min(stats, axis=0) # each column

array([1, 2, 3])

In [44]:
np.min(stats, axis=1) # each row

array([1, 4])

In [45]:
np.max(stats)

6

In [46]:
np.sum(stats)

21

In [47]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reshape

In [48]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((4,2)) # (2,2,2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## vertically stacking vectors

In [49]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

## horizontally stacking vectors

In [50]:
h1 = np.full((2,3),0)
h2 = np.full((2,2),1)
np.hstack([h1,h2])

array([[0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1]])

# Boolean Masking & Advanced Indexing

In [51]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
data >= 5

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [53]:
(data > 3) & (data < 7)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [54]:
data[data>5]

array([6, 7, 8, 9])

In [55]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [56]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [57]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

### .any() 

In [58]:
np.any(data > 7, axis=0) # each col

array([False,  True,  True])

In [59]:
np.any(data > 7, axis=1) # each row

array([False, False,  True])

### .all()

In [60]:
np.all(data > 6, axis=1)

array([False, False,  True])

# Load data from file without pandas

In [63]:
file_data = np.genfromtxt('Desktop/data.txt', delimiter=',')
file_data = file_data.astype('int32')
# print(file_data)

In [64]:
0 X 0 0 0
0 0 X 0 0
0 0 0 X 0
0 0 0 0 X
0 0 0 0 0
0 0 0 0 0

a[[0,1,2,3],[1,2,3,4]]

0 0 0 X X
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 X X
0 0 0 X X

a[[0,4,5],[3:]]

In [65]:
output = np.full((5,5),1)

z = np.full((3,3),0)
z[1,1] = 9

output[1:4,1:4] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
